### ISSUE TITLE
Modules and Wordnet

### ISSUE THREAD

**Issue by Chaiavi** [dpdearing/nlp#2]
I understand that this was done in purpose and is not a bug.

But, it is such a pain in the a$$ to download all the modules from openNLP and find the right files from wordnet (I still think there is a bug here where the file names are different [maybe a windows/unix issue] as the wordnet files need to be renamed and then the test fails (maybe just version mismatch).

Can you please consider having all of the files in the github repository so one can just download the library and start using it out of the box ?

And for advanced users you can maintain the links to the sources of these files so they can update them as they see fit.

What do you think ?

**Comment by dpdearing** [comment]
I get what you're saying.  Originally this was so that any changes to those model files don't need to be updated in the repo, but I don't think they have actually changed in many years.

The problem with this is that the file sizes are large, which makes the git source code repo large.  Not everyone necessarily needs every file (modules, languages) so you force everyone to download the entire thing.

I'm open to alternatives, but am leaning towards keeping them out of the repository itself.  Maybe the README can just be cleaned up to highlight what is needed?  Or some additional error handling to spit out a better error message when some file is missing?

**Comment by Chaiavi** [comment]
Personally I think that the size (about 70 mb) isn't such an issue these days, as disks and bandwith get bigger and bigger.

But I respect your great work here and will try to see if i can help updating the readme file with some more accurate instructions as where to find the files and where to copy them.

If I will get to it I can try and have a look at the error handling for more informative errors in these issues, but am not promising anything  :-)

**Comment by Chaiavi** [comment]
Please have a look at my pull request:
https://github.com/dpdearing/nlp/pull/3

After much work on the project I have a compromise about the files which might work, but let's focus on the current pull request and if everything goes well I will suggest it in a new issue.

**Comment by dpdearing** [comment]
I created my own branch off of your pull request and cleaned it up a bit.  Take a look at 93b8327 and let me know if this addresses the concerns.  Thanks for your help!

**Comment by dpdearing** [comment]
I created my own branch off of your pull request and cleaned it up a bit. Take a look at 77ddf63...93b8327f  and let me know if this addresses the concerns. Thanks for your help!

**Comment by Chaiavi** [comment]
All looks good

One small thing though, there is no good handling to a missing properties file.
Maybe catch Exception and do a System.exit() here?:
https://github.com/dpdearing/nlp/blob/opennlp_model_stability/src/main/java/com/dpdearing/nlp/opennlp/OpenNlpToolkit.java#L538

Just debug that one and the code looks much better than it was originally

**Comment by dpdearing** [comment]
Is it really all that different from when the resource files are missing?  In either case the file is missing and there's not a lot that the OpenNlpToolkit can do, but exiting completely seems extreme.  Shouldn't that be the decision of the code that uses this library?

**Comment by Chaiavi** [comment]
Agreed.

But currently when the properties file is missing it just throws a NullPointerException without any explanation.

Something should be done there

**Comment by dpdearing** [comment]
Oh now I understand.   OK, I made another change in 521910e and merged it all back into the master branch.  I'll mark this issue as closed, but open to hearing your thoughts about the files in a new issue.  Thanks for your help!

The WordNet and Coreference ones are a pain and are probably stable enough that including them in the project wouldn't be that bad.  Still, curious to hear your ideas.
