### ISSUE TITLE
Adding some of the "3rd party" files into the project

### ISSUE THREAD

**Issue by Chaiavi** [dpdearing/nlp#5]
Currently the user needs to download the project, then download three sets of files: 
- Coref files
- Wordnet files
- OpenNLP model files

From experience, it is a big hassle to find/tweak the above files in order to add them to the project and into the right directories etc.

So my suggestion is to add them to the project.

But there are reasons also not to add them as follows:
1.  These files take about 80mb of project space which is quite big
2. There might be a difference between projects working under windows or linux concerning the naming of the `coref`files
3. If we will put the files into the project we will probably lock it to be an NLP Sandbox for **English**(and not other languages)
4. We are blocking the project from being upgraded by default, as we are locking the files to these specific models while the user could have downloaded and added other models which fit him more / are more updated

**_I am opening this issue as a stage to discussion hoping we can find the best solution and work towards it._**

Addressing the concerns I have raised above:
1. If we add only the *_wordnet and the coref files *_(which actually are the most painful to add to the project in the first place) we are adding 27mb as the bulk of the space is taken by the opennlp model files
1.b. We can also compress the above files and uncompress them in runtime (compressed they consume 8mb, but it might not be worth the complexity it might add)
2. By default the naming is different but if we put the files in the lib directory and reference them from the project I think that it will work out of the box on all systems
3. _This can be a concern if you want to make it multilangual and can be a blocker, so this is a project roadmap decision the owner should take_.
4. IMHO, most users are simple users which prefer us to put the files into place and save them the hassle, the advanced users will probably know how to upgrade the files if they want to, and might probably skip this project all together as they will load OpenNLP directly...

What do you think ?

**Comment by dpdearing** [comment]
I stalled to think on this (and got busy elsewhere), but I do agree that including the files is helpful.  And I had forgotten that some of the files are particularly troublesome for certain operating systems.

I'm not wild about only including a subset of the files.  All or nothing seems the least confusing.  Also, uncompressing the files at runtime is an unnecessary hassle.  It saves some space, but seems like a half-solution.

I think the properties file allows for redirecting to files for different languages.  If that's true, then it's not terribly hard for users to update to other languages--not much worse than the current situation, anyway.

Some things I'd like to consider before adding files directly:
- Is redirecting to other languages through the properties file easy?  Maybe add some comments to that file.
- If git handles symlinks correctly, that might help with the operating system issues of different names for the same files.
- Any licensing issues with directly including those files?

**Comment by dpdearing** [comment]
I dropped 562a59c which had some problems.  It was replaced by 9cede40.
